name: customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  sign_in_with_apple: ^6.1.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutterflow_paginate_firestore: ^1.0.3+1
  firebase_storage: ^12.3.1

  firebase_database: ^11.0.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  auto_size_text_field: ^2.2.4

  get: 4.6.6
  provider: ^6.1.2

  country_code_picker: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg:
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0

  otp_text_field: ^1.1.3

  crypto: ^3.0.5
  intl: ^0.19.0

  timelines_plus: ^1.0.3
  google_places_flutter: ^2.0.8
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  map_launcher: ^3.5.0

  geocoding: ^3.0.0
  geoflutterfire2: ^2.3.15
  googleapis_auth: ^1.6.0
  dio: ^5.7.0
  uuid: ^4.5.0

  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  flutter_widget_from_html: ^0.15.2
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.2

  #payment_dependencies
  flutter_stripe: ^11.1.0
  #  flutter_paypal_native: ^2.1.0
  razorpay_flutter: ^1.3.7
  mercadopago_sdk: ^1.3.0
  url_launcher: ^6.3.0
  dotted_border: ^2.1.0
  win32: ^5.5.4
  flutterwave_standard_smart: ^1.0.4
  animated_snack_bar: ^0.4.0
  path: ^1.9.0
  sqflite: ^2.4.0
  permission_handler: ^11.3.1
  change_app_package_name: ^1.4.0

dependency_overrides:
  http: ^1.2.2
  web: ^1.0.0
  rxdart: ^0.28.0
  cloud_firestore: ^5.4.2
  package_info_plus: ^8.0.2
  geolocator: ^13.0.1
  google_maps_place_picker_mb: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/
